### ISSUE TITLE
have problem

### ISSUE THREAD

**Issue by hithto** [xlsdg/react-echarts-v3#3]
Module parse failed: C:\DTweb\DT.Web\Scripts\mobile\node_modules\react-echarts-v3\lib\index.jsx Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import ECharts from 'echarts';
| import Wrapper from './wrapper.jsx';

**Comment by xlsdg** [comment]
see https://github.com/xlsdg/react-echarts-v3/issues/1
