### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. WARNING in console

### ISSUE THREAD

**Issue by chin2km** [xlsdg/react-echarts-v3#4]
Have been getting lots of console warnings recently because of `Passive Event Listeners`. 
Its because of recent introduction of Passive Event listeners in new versions of Chrome/Firefox. The passive event listeners is aimed at improving scrolling performance.

You can read more about it here -> https://stackoverflow.com/questions/37721782/what-are-passive-event-listeners

It needs to be fixed in the library because thats where the event listeners are added. And there is no way one will be able to suppress these warning in their project. Please add support for Passive Event listeners.

**Comment by xlsdg** [comment]
You can ask at https://github.com/ecomfe/echarts/issues.
